apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deployment #deployment name

spec:
  replicas: 1 #only 1 copy of the pod
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: stephengrider/multi-client
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
